"""
extract_montage_frames.py pulls the montage panels out of the annotated videos
the pipeline writes, so each panel is a frame of the system's own output rather
than a redrawing of it. It performs no detection, tracking or annotation: every
overlay in the extracted frames was rendered by main.py.

Each panel is chosen against a committed measurement rather than by eye, and the
reason is carried on the panel itself so a caption can be written from it:

  clip_2 frame 129   the spurious interception the event detector emits where the
                     ground truth records a completed pass at frame 120, which is
                     the outcome that refutes prediction E1
  clip_3 frame 153   inside the contiguous run of 45 frames Stage 8 could not map,
                     where the camera pans at a median 20.05 px per frame against
                     1.62 px outside it
  clip_2 frame 12    a frame of the same system working: ground truth holds track 9
                     continuously from frame 2 to 27, clip_2 maps all 174 of its
                     frames, and the clip's first spurious event is not until
                     frame 22

Frames are read by a single sequential pass per clip, checking each index against
the set required, rather than by seeking with CAP_PROP_POS_FRAMES. Seeking is
unreliable on compressed formats such as this project's XVID .avi outputs:
decoding resumes from the nearest keyframe, so a seek can silently return a
neighbouring frame instead of the one asked for, and exact frame identity is the
entire point of this script. No clip reaches 250 frames, so a full pass is
effectively free.

Unlike the measurement scripts this one cannot run from a fresh clone. It reads
the annotated videos, which are regenerated by running main.py per clip, which in
turn needs the two checkpoints from the GitHub Release in models/.
"""
from __future__ import annotations

import sys
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

import cv2

ANNOTATED_VIDEO_TEMPLATE = 'data/outputs/{clip}_annotated.avi'
OUTPUT_DIR = Path('data/outputs/montage_frames')

# Alternates either side of each panel frame. Re-running the pipeline to recover
# from one cluttered frame costs a full inference pass over the clip, so the
# neighbours are cheap insurance taken at extraction time. They are named as
# alternates so they cannot be mistaken for the measured frame itself.
ALTERNATE_OFFSETS = (-3, 3)


@dataclass(frozen=True)
class Panel:
    """One montage panel: the frame it is taken from and the measurement that chose it."""

    key: str
    clip: str
    frame: int
    role: str
    why: str


PANELS = (
    Panel(
        key='a',
        clip='clip_2',
        frame=129,
        role='phantom_interception',
        why='spurious interception; ground truth records one completed pass at frame 120 (refutes E1)',
    ),
    Panel(
        key='b',
        clip='clip_3',
        frame=153,
        role='unmapped_run',
        why='inside the 45-frame unmapped run; camera pans at a median 20.05 px per frame here',
    ),
    Panel(
        key='c',
        clip='clip_2',
        frame=12,
        role='working',
        why='track 9 holds continuously from frame 2 to 27; clip_2 maps all 174 frames',
    ),
)


def require_annotated_video(clip: str) -> str:
    """Return one clip's annotated video path, raising a clear error when the pipeline has not written it."""
    path = ANNOTATED_VIDEO_TEMPLATE.format(clip=clip)
    if not Path(path).exists():
        raise FileNotFoundError(
            f'{path} not found. The annotated videos are produced by running '
            f'`python main.py --input data/raw/{clip}.mp4`, which needs models/ball.pt and the '
            f'keypoint checkpoint named in config/default.yaml, both downloaded from the GitHub '
            f'Release into models/. They are regenerated rather than committed, so an absent one '
            f'means the pipeline has not been run on this clip.'
        )
    return path


def panel_filenames(panel: Panel) -> dict[int, str]:
    """Return the frame indices one panel needs, mapped to the filenames they are written under."""
    stem = f'panel_{panel.key}_{panel.clip}_f{panel.frame}_{panel.role}'
    filenames = {panel.frame: f'{stem}.png'}
    for offset in ALTERNATE_OFFSETS:
        index = panel.frame + offset
        filenames[index] = f'{stem}_alt_f{index}.png'
    return filenames


def required_frames(clip: str) -> dict[int, list[str]]:
    """Return every frame index one clip must yield, mapped to the filenames written from it."""
    required: dict[int, list[str]] = {}
    for panel in PANELS:
        if panel.clip != clip:
            continue
        for index, filename in panel_filenames(panel).items():
            required.setdefault(index, []).append(filename)
    return required


def extract_clip(clip: str, required: dict[int, list[str]]) -> tuple[int, list[str]]:
    """Decode one clip from frame 0, writing every required frame, and return the count written with any warnings."""
    path = require_annotated_video(clip)
    modified = datetime.fromtimestamp(Path(path).stat().st_mtime).strftime('%Y-%m-%d %H:%M:%S')
    print(f'[{clip}] {path} (written {modified})')

    capture = cv2.VideoCapture(path)
    if not capture.isOpened():
        raise IOError(
            f'{path} could not be opened. The file exists, so this is a codec or a truncated-write '
            f'problem rather than a missing pipeline run.'
        )
    reported_frames = int(capture.get(cv2.CAP_PROP_FRAME_COUNT))

    written: set[int] = set()
    count = 0
    index = 0
    while True:
        success, frame = capture.read()
        if not success:
            break
        for filename in required.get(index, []):
            output_path = OUTPUT_DIR / filename
            if not cv2.imwrite(str(output_path), frame):
                raise IOError(f'{output_path} could not be written.')
            print(f'  wrote {output_path}')
            count += 1
        if index in required:
            written.add(index)
        index += 1
    capture.release()

    warnings = []
    for missing in sorted(set(required) - written):
        if missing < 0:
            reason = 'negative index, so an alternate offset runs off the start of the clip'
        elif missing >= reported_frames:
            reason = f'beyond the clip, which reports {reported_frames} frames'
        else:
            reason = 'the frame could not be decoded'
        for filename in required[missing]:
            warnings.append(f'[{clip}] frame {missing} not extracted for {filename}: {reason}')

    print(f'  decoded {index} frames, reported {reported_frames}')
    return count, warnings


def main() -> int:
    """Extract every panel frame and its alternates, and report what each panel is evidence of."""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    print('Montage panels:')
    for panel in PANELS:
        print(f'  panel {panel.key}: {panel.clip} frame {panel.frame}, {panel.why}')
    print()

    total = 0
    warnings: list[str] = []
    for clip in dict.fromkeys(panel.clip for panel in PANELS):
        count, clip_warnings = extract_clip(clip, required_frames(clip))
        total += count
        warnings.extend(clip_warnings)

    print(f'\nWrote {total} frame(s) to {OUTPUT_DIR}')
    for warning in warnings:
        print(f'WARNING: {warning}')

    # A missing alternate is a nuisance; a missing panel frame means the montage
    # cannot be built from this run, so it is worth a non-zero exit rather than a
    # line of output that scrolls past.
    missing_panels = [
        panel for panel in PANELS
        if not (OUTPUT_DIR / panel_filenames(panel)[panel.frame]).exists()
    ]
    if missing_panels:
        print(f'\nMissing panel frame(s): {", ".join(panel.key for panel in missing_panels)}')
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
