"""
plot_montage_figure.py composites the three montage panels into the figure the
dissertation prints. It performs no detection, tracking or annotation and adds
nothing to the frames: every overlay in the panels was rendered by main.py, and
this script only crops, places and letters them.

Each panel is cropped to a common 445 x 250 window rather than shown whole. At
18.0 cm across two columns a full 1280 px frame lands at 5.9 cm, which puts the
event caption in panel (b) at 2.1 pt and the 'NO HOMOGRAPHY' watermark in panel
(c) at 4.6 pt: both below the 6 pt floor, so the panels would have been printed
showing something no reader could read. The common crop magnifies every panel by
2.87x, which brings the caption to 6.0 pt. The cost is stated rather than hidden:
panel (b) no longer contains the cyan possession box on player 7 at x 758-831,
because a window wide enough to hold both it and the caption would be 509 px and
would not reach 6 pt. The caption names the players instead.

The crop windows are hand-chosen, so the script measures each panel's region of
interest out of the pixels and aborts unless the window actually contains it. A
montage cropped past the thing it exists to show is worse than no montage, so
that check is fatal, as are the checks that each feature still clears its size
threshold at the printed width.

Unlike the measurement scripts this one cannot run from a fresh clone. It reads
the extracted panels, which scripts/extract_montage_frames.py pulls out of the
annotated videos, which are regenerated by running main.py per clip.
"""
from __future__ import annotations

import sys
from dataclasses import dataclass
from pathlib import Path

import matplotlib

# Selected before pyplot is imported. This script only ever writes files, and the
# environment the results were produced in is headless.
matplotlib.use('Agg')

import matplotlib.patheffects as path_effects  # noqa: E402
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
from PIL import Image  # noqa: E402

PANEL_DIR = Path('data/outputs/montage_frames')
OUTPUT_DIR = Path('data/outputs/figures')
OUTPUT_STEM = 'fig3_montage'
OUTPUT_SUFFIXES = ('.pdf', '.png')

# Full width of an IEEE two-column A4 page, so the figure spans both columns.
FIGURE_WIDTH_CM = 18.0
GUTTER_CM = 0.15
CM_PER_IN = 2.54

# The common crop, in source pixels. 445 wide is what brings panel (b)'s caption
# to exactly 6 pt at the panel width below; 250 keeps the source 16:9 aspect so
# the three panels are the same height without any of them being stretched.
CROP_WIDTH_PX = 445
CROP_HEIGHT_PX = 250

SOURCE_SIZE_PX = (1280, 720)

# Every panel is placed at its native pixel count, so this is the real resolution
# of the printed figure rather than a number chosen to look reassuring.
PNG_DPI = 383  # two device pixels per source pixel, so the PNG doubles cleanly

LABEL_FONT_SIZE = 8.5
LABEL_INSET_CM = 0.10
MINIMUM_FONT_SIZE_PT = 6.0

# The caption in panel (b) is the reason for the crop, so the threshold it has to
# clear is written down rather than left as a thing that was checked once.
CAPTION_MINIMUM_PT = 6.0


@dataclass(frozen=True)
class Panel:
    """One panel: its source file, the window cropped from it, and the feature that window must contain."""

    key: str
    filename: str
    crop: tuple[int, int, int, int]
    feature: str
    detector: str


PANELS = (
    Panel(
        key='a',
        filename='panel_c_clip_2_f12_working.png',
        crop=(218, 234, 663, 484),
        feature='the cyan possession box and the player number beneath it',
        detector='cyan',
    ),
    Panel(
        key='b',
        filename='panel_a_clip_2_f129_phantom_interception.png',
        crop=(835, 0, 1280, 250),
        feature='the two-line pass and interception caption',
        detector='caption',
    ),
    Panel(
        key='c',
        filename='panel_b_clip_3_f153_unmapped_run.png',
        crop=(0, 470, 445, 720),
        feature='the minimap, empty because no homography was available',
        detector='minimap',
    ),
)


def panel_width_cm() -> float:
    """Return one panel's printed width, the figure less its two gutters shared three ways."""
    return (FIGURE_WIDTH_CM - (len(PANELS) - 1) * GUTTER_CM) / len(PANELS)


def cm_per_pixel() -> float:
    """Return how much of the page one source pixel occupies once cropped and placed."""
    return panel_width_cm() / CROP_WIDTH_PX


def points(pixels: float) -> float:
    """Return a source-pixel span as printed points."""
    return pixels * cm_per_pixel() / CM_PER_IN * 72.0


def require_panel(panel: Panel) -> Path:
    """Return one panel's path, raising a clear error when the extraction step has not been run."""
    path = PANEL_DIR / panel.filename
    if not path.exists():
        raise FileNotFoundError(
            f'{path} not found. The montage panels are extracted by '
            f'`python scripts/extract_montage_frames.py`, which reads the annotated videos in '
            f'data/outputs/. Those are regenerated by running main.py per clip rather than '
            f'committed, so an absent panel means the extraction has not been run here.'
        )
    return path


def feature_bounds(image: np.ndarray, detector: str) -> tuple[int, int, int, int]:
    """Return the pixel bounds of a panel's region of interest, found in the image rather than assumed."""
    if detector == 'cyan':
        # The possession highlight is drawn in a saturated cyan that nothing in
        # broadcast footage matches. The scoreboard band carries a similar teal,
        # so the search stops above it.
        mask = (image[:, :, 0] < 90) & (image[:, :, 1] > 200) & (image[:, :, 2] > 200)
        mask[560:, :] = False
    elif detector == 'caption':
        # The event overlay is the only green and orange text in the frame.
        green = (image[:, :, 1] > 170) & (image[:, :, 0] < 140) & (image[:, :, 2] < 140)
        orange = ((image[:, :, 0] > 200) & (image[:, :, 1] > 110)
                  & (image[:, :, 1] < 200) & (image[:, :, 2] < 90))
        mask = green | orange
        mask[70:, :] = False
    elif detector == 'minimap':
        # The minimap is the pale panel inset into the bottom left corner.
        mask = np.zeros(image.shape[:2], dtype=bool)
        region = image[560:720, 0:300].mean(axis=2) > 150
        mask[560:720, 0:300] = region
    else:
        raise ValueError(f'Unknown detector {detector!r}.')

    ys, xs = np.nonzero(mask)
    if not len(xs):
        raise ValueError(
            f'The {detector} feature could not be found in the panel at all, so the frame is not '
            f'the one this script was written against.'
        )
    return int(xs.min()), int(ys.min()), int(xs.max()), int(ys.max())


def verify_crop_contains_feature(panel: Panel, image: np.ndarray) -> tuple[int, int]:
    """Confirm one panel's crop window holds its whole region of interest, returning the margins to the window edge."""
    left, top, right, bottom = panel.crop
    x0, y0, x1, y1 = feature_bounds(image, panel.detector)
    if x0 < left or y0 < top or x1 > right or y1 > bottom:
        raise ValueError(
            f'Panel ({panel.key}) is cropped to {panel.crop}, which cuts {panel.feature}: '
            f'the feature spans x {x0}-{x1}, y {y0}-{y1}. The panel would be printed missing the '
            f'one thing it exists to show.'
        )
    return min(x0 - left, right - x1), min(y0 - top, bottom - y1)


def verify_geometry() -> None:
    """Confirm the crop lies inside the source frame and keeps the frame's aspect ratio."""
    width, height = SOURCE_SIZE_PX
    for panel in PANELS:
        left, top, right, bottom = panel.crop
        if right - left != CROP_WIDTH_PX or bottom - top != CROP_HEIGHT_PX:
            raise ValueError(
                f'Panel ({panel.key}) is cropped to {right - left}x{bottom - top}, not the common '
                f'{CROP_WIDTH_PX}x{CROP_HEIGHT_PX}. The panels would not share a height.'
            )
        if left < 0 or top < 0 or right > width or bottom > height:
            raise ValueError(
                f'Panel ({panel.key})\'s crop {panel.crop} runs outside the {width}x{height} frame.'
            )

    source_aspect = width / height
    crop_aspect = CROP_WIDTH_PX / CROP_HEIGHT_PX
    if abs(source_aspect - crop_aspect) > 0.01:
        raise ValueError(
            f'The crop aspect {crop_aspect:.3f} does not match the source {source_aspect:.3f}, so '
            f'the panels would be stretched relative to the footage.'
        )


def verify_caption_size(image: np.ndarray) -> float:
    """Confirm panel (b)'s caption clears the 6 pt floor at the printed width, returning its size in points."""
    green = (image[:, :, 1] > 170) & (image[:, :, 0] < 140) & (image[:, :, 2] < 140)
    rows = np.nonzero(green[0:70, :].sum(axis=1) > 1)[0]
    size = points(rows.max() - rows.min() + 1)
    if size < CAPTION_MINIMUM_PT:
        raise ValueError(
            f'The event caption prints at {size:.2f} pt, below the {CAPTION_MINIMUM_PT:.0f} pt floor. '
            f'A narrower crop would raise it: at {CROP_WIDTH_PX} px the magnification is '
            f'{SOURCE_SIZE_PX[0] / CROP_WIDTH_PX:.2f}x.'
        )
    return size


def label_colour(image: np.ndarray, panel: Panel) -> tuple[str, str, float]:
    """Return the label's fill, its outline, and the mean luminance of the patch it sits on."""
    # The corner a label lands on is not uniform in any of these frames, so the
    # fill is chosen from the patch's own luminance and then given a contrasting
    # outline. The outline is what makes the choice safe: panel (a)'s corner runs
    # from luminance 2 to 241 within the space of the two glyphs, and no single
    # flat colour is legible across that range.
    inset = round(LABEL_INSET_CM / cm_per_pixel())
    left, top = panel.crop[0], panel.crop[1]
    patch = np.array(Image.fromarray(image).convert('L')).astype(float)[
        top + inset:top + inset + 14, left + inset:left + inset + 24]
    mean = float(patch.mean())
    return ('white', 'black', mean) if mean <= 128 else ('black', 'white', mean)


def render(panels: list[tuple[Panel, np.ndarray, str, str]]) -> list[Path]:
    """Place the cropped panels side by side with their letters, and write the figure."""
    panel_cm = panel_width_cm()
    height_cm = panel_cm * CROP_HEIGHT_PX / CROP_WIDTH_PX
    figure = plt.figure(figsize=(FIGURE_WIDTH_CM / CM_PER_IN, height_cm / CM_PER_IN))

    for index, (panel, image, fill, outline) in enumerate(panels):
        left, top, right, bottom = panel.crop
        # Axes span the panel exactly: no border, no title, no padding, so the
        # only white in the figure is the gutter between panels.
        axes = figure.add_axes([
            index * (panel_cm + GUTTER_CM) / FIGURE_WIDTH_CM, 0.0,
            panel_cm / FIGURE_WIDTH_CM, 1.0,
        ])
        axes.imshow(image[top:bottom, left:right], interpolation='nearest', aspect='auto')
        axes.set_xticks([])
        axes.set_yticks([])
        for spine in axes.spines.values():
            spine.set_visible(False)
        text = axes.text(
            LABEL_INSET_CM / panel_cm, 1.0 - LABEL_INSET_CM / height_cm, f'({panel.key})',
            transform=axes.transAxes, fontsize=LABEL_FONT_SIZE, color=fill,
            ha='left', va='top', fontweight='bold',
        )
        text.set_path_effects([
            path_effects.withStroke(linewidth=1.4, foreground=outline),
        ])

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    written = []
    for suffix in OUTPUT_SUFFIXES:
        path = OUTPUT_DIR / f'{OUTPUT_STEM}{suffix}'
        figure.savefig(path, dpi=PNG_DPI)
        written.append(path)
    plt.close(figure)
    return written


def print_table(title: str, headers: list[str], rows: list[list[str]]) -> None:
    """Print one aligned results table."""
    widths = (
        [max(len(str(cell)) for cell in column) for column in zip(headers, *rows)] if rows
        else [len(header) for header in headers]
    )
    print(f'\n{title}')
    print('  '.join(header.ljust(width) for header, width in zip(headers, widths)))
    for row in rows:
        print('  '.join(str(cell).ljust(width) for cell, width in zip(row, widths)))


def main() -> int:
    """Verify every crop against the feature it must contain, then composite and write the figure."""
    verify_geometry()

    panel_cm = panel_width_cm()
    height_cm = panel_cm * CROP_HEIGHT_PX / CROP_WIDTH_PX
    dpi = CROP_WIDTH_PX / (panel_cm / CM_PER_IN)
    print(f'Figure {FIGURE_WIDTH_CM:.1f} cm by {height_cm:.2f} cm, spanning both columns.')
    print(f'Each panel {panel_cm:.2f} cm wide from a {CROP_WIDTH_PX} px crop, '
          f'{SOURCE_SIZE_PX[0] / CROP_WIDTH_PX:.2f}x magnification, {dpi:.1f} effective dpi.')

    loaded = []
    rows = []
    for panel in PANELS:
        image = np.array(Image.open(require_panel(panel)).convert('RGB'))
        if (image.shape[1], image.shape[0]) != SOURCE_SIZE_PX:
            raise ValueError(
                f'Panel ({panel.key}) is {image.shape[1]}x{image.shape[0]}, not '
                f'{SOURCE_SIZE_PX[0]}x{SOURCE_SIZE_PX[1]}, so the common crop does not mean the '
                f'same thing across the three panels.'
            )
        margin_x, margin_y = verify_crop_contains_feature(panel, image)
        fill, outline, mean = label_colour(image, panel)
        loaded.append((panel, image, fill, outline))
        x0, y0, x1, y1 = feature_bounds(image, panel.detector)
        rows.append([
            f'({panel.key})',
            f'{x1 - x0 + 1}x{y1 - y0 + 1} px',
            f'{(x1 - x0 + 1) * cm_per_pixel():.2f} x {(y1 - y0 + 1) * cm_per_pixel():.2f} cm',
            f'{min(margin_x, margin_y)} px',
            f'{fill} on {mean:.0f}',
        ])

    print_table(
        'Region of interest, measured from the pixels and checked against the crop',
        ['panel', 'feature', 'printed size', 'clearance', 'label'],
        rows,
    )

    caption_pt = verify_caption_size(loaded[1][1])
    print(f'\nPanel (b) caption prints at {caption_pt:.2f} pt, at or above the '
          f'{CAPTION_MINIMUM_PT:.0f} pt floor.')

    print()
    for path in render(loaded):
        print(f'Wrote {path}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
